#!/usr/bin/env python3
"""Generate compact Unicode-property ranges for the GPT-2 tokenizer."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

try:
    import regex
except ImportError as exception:
    raise SystemExit(
        "generate_unicode_ranges.py requires the 'regex' Python package"
    ) from exception


ROOT_DIRECTORY = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT_DIRECTORY / "src" / "unicode_ranges.inc"
MAXIMUM_CODE_POINT = 0x10FFFF


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate the Unicode range tables used by the GPT-2 tokenizer."
        )
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"generated include path (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing if the generated file is stale",
    )
    return parser.parse_args()


def property_ranges(pattern: str) -> list[tuple[int, int]]:
    matcher = regex.compile(pattern)
    ranges: list[tuple[int, int]] = []
    range_start: int | None = None
    previous: int | None = None

    for code_point in range(MAXIMUM_CODE_POINT + 1):
        matches = matcher.fullmatch(chr(code_point)) is not None
        if matches:
            if range_start is None:
                range_start = code_point
            elif previous is not None and code_point != previous + 1:
                ranges.append((range_start, previous))
                range_start = code_point
            previous = code_point
        elif range_start is not None:
            if previous is None:
                raise AssertionError("Unicode range has no final code point")
            ranges.append((range_start, previous))
            range_start = None
            previous = None

    if range_start is not None:
        if previous is None:
            raise AssertionError("Unicode range has no final code point")
        ranges.append((range_start, previous))

    return ranges


def format_table(
    name: str,
    ranges: list[tuple[int, int]],
) -> list[str]:
    lines = [
        f"constexpr std::array<CodePointRange, {len(ranges)}> {name}{{{{"
    ]
    for first, last in ranges:
        lines.append(
            "    {char32_t{0x"
            f"{first:06X}"
            "}, char32_t{0x"
            f"{last:06X}"
            "}},"
        )
    lines.append("}};")
    return lines


def generate() -> str:
    tables = (
        ("letter_ranges", property_ranges(r"\p{L}")),
        ("number_ranges", property_ranges(r"\p{N}")),
        ("whitespace_ranges", property_ranges(r"\s")),
    )

    lines = [
        "// Generated by tools/generate_unicode_ranges.py; do not edit.",
        f"// Python regex version: {regex.__version__}",
        "// Properties: Unicode General_Category L, General_Category N, and \\s.",
        "",
    ]
    for index, (name, ranges) in enumerate(tables):
        if index != 0:
            lines.append("")
        lines.extend(format_table(name, ranges))

    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    output = args.output.resolve()
    generated = generate()

    if args.check:
        try:
            current = output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"Unicode range table is missing: {output}", file=sys.stderr)
            return 1

        if current != generated:
            print(f"Unicode range table is stale: {output}", file=sys.stderr)
            return 1

        print(f"Unicode range table is current: {output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
